//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts : Persons
    {
        public string password { get; set; }
        public string phoneNumber { get; set; }

        public Accounts()
        {
        }

        public Accounts(string firstName, string lastName, string phoneNumber, string emailAddres, string password)
        {
            this.firstName = firstName;
            this.lastName = lastName;
            this.phoneNumber = phoneNumber;
            this.email = emailAddres;
            this.password = password;
        }


    }
}
