//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int id { get; set; }

        [Display(Name = "Description:")]
        public string description { get; set; }

        [Display(Name = "Location:")]
        public string location { get; set; }

        [Display(Name = "Price:")]
        public decimal price { get; set; }

        [Display(Name = "Name:")]
        public string name { get; set; }

        [Display(Name = "Starting time:")]
        public System.DateTime startTime { get; set; }

        [Display(Name = "End time:")]
        public Nullable<System.DateTime> endTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual Specials Specials { get; set; }
        public virtual Films Films { get; set; }
        public virtual Restaurants Restaurants { get; set; }
    }
}
