//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapLocations
    {
        public int id { get; set; }
        public string placeName { get; set; }
        public double geoLong { get; set; }
        public double geoLat { get; set; }
        public string adress { get; set; }
        public string city { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string imagePath { get; set; }
        public string markerPath { get; set; }
    }
}
