//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Specials : Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specials()
        {
            this.SpecialTicket = new HashSet<SpecialTicket>();
        }

        [Required(AllowEmptyStrings = false)]
        public string host { get; set; }
        [Required(AllowEmptyStrings = false)]
        public int capacity { get; set; }
        [Required(AllowEmptyStrings = false)]
        [DataType(DataType.DateTime)]
        public System.DateTime startTime { get; set; }
        [Required(AllowEmptyStrings = false)]
        [DataType(DataType.DateTime)]
        public System.DateTime endTime { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialTicket> SpecialTicket { get; set; }
    }
}
