//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        public int id { get; set; }
        public int orderItemId { get; set; }
        public int restaurantId { get; set; }
        public System.DateTime dateTime { get; set; }
    
        public virtual OrderItems OrderItems { get; set; }
    }
}
