//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_IHFF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public int itemId { get; set; }
        public string name { get; set; }
        public System.TimeSpan timeOpen { get; set; }
        public System.TimeSpan timeClosed { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
